# Generated by Django 4.0.2 on 2022-02-19 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['complete', '-modified_on']},
        ),
    ]
