# Generated by Django 4.0.2 on 2022-02-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_task_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='modified_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
